name: My First Github Actions
on: [push]
jobs:
  project-building:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install node_modules
        run: npm install
      - name: Build the Project
        run: npm run build
      - name: Sets the vercel env
        run: |
          cd dist
          mkdir .vercel
          cd .vercel
          touch project.json
          echo "{"orgId":"GsufK1gEBBwXPi8gZ1oReqJX","projectId":"prj_X5bq5NcUme2X6Xaahb0tVLSdgDz7"}" > project.json
      - name: Deploying the project
        run: yarn deploy
      - name: Setup Finished
        run: echo "Successfully build the project"
